version: 0.2

phases:
  pre_build:
    commands:
      - echo "Iniciando a fase de pre-build..."
      - echo Fazendo login no ECR...      
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 654654346517.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build iniciado em `date`
      - echo Gerando imagem do Container...
      - docker build -t repository_glpi .
      - docker tag repository_glpi:latest 654654346517.dkr.ecr.us-east-1.amazonaws.com/repository_glpi:latest

  post_build:
    commands:
      - echo Build finalizado com sucesso em `date`
      - echo Fazendo push da imagem para o ECR...
      - docker push 654654346517.dkr.ecr.us-east-1.amazonaws.com/repository_glpi:latest
